export const carData = {
  "Nissan": ["Versa", "Sentra", "March", "Tsuru", "Altima", "Kicks", "X-Trail", "Frontier", "NP300", "Pathfinder", "Tiida", "Urvan"],
  "Chevrolet": ["Aveo", "Spark", "Beat", "Chevy", "Onix", "Trax", "Equinox", "Silverado", "Colorado", "Malibu", "Cruze", "Captiva", "Suburban"],
  "Volkswagen": ["Jetta", "Golf", "Vento", "Polo", "Tiguan", "Taos", "Bora", "Saveiro", "Amarok", "Virtus"],
  "Toyota": ["Corolla", "Yaris", "Hilux", "RAV4", "Camry", "Prius", "Avanza", "Tacoma", "Sienna", "Hiace"],
  "Honda": ["Civic", "CR-V", "Accord", "City", "HR-V", "Fit", "Pilot", "Odyssey", "BR-V"],
  "Ford": ["Fiesta", "Figo", "Focus", "Mustang", "Escape", "Explorer", "F-150", "Lobo", "Ranger", "Edge", "EcoSport"],
  "Mazda": ["Mazda2", "Mazda3", "Mazda6", "CX-3", "CX-30", "CX-5", "CX-9"],
  "Hyundai": ["Grand i10", "Accent", "Elantra", "Tucson", "Creta", "Santa Fe", "HB20"],
  "Kia": ["Rio", "Forte", "Sportage", "Sorento", "Soul", "Seltos", "Optima"],
  "Dodge": ["Attitude", "Neon", "Journey", "Charger", "Challenger", "Durango", "Ram"],
  "Seat": ["Ibiza", "Leon", "Arona", "Ateca", "Tarraco", "Toledo"],
  "Renault": ["Kwid", "Duster", "Koleos", "Stepway", "Logan", "Kangoo", "Captur", "Oroch"],
  "Suzuki": ["Swift", "Ignis", "Ertiga", "Vitara", "Jimny", "S-Cross"],
  "BMW": ["Serie 1", "Serie 3", "Serie 5", "X1", "X3", "X5", "X7"],
  "Mercedes-Benz": ["Clase A", "Clase C", "Clase E", "GLA", "GLC", "GLE", "Sprinter"],
  "Audi": ["A1", "A3", "A4", "Q2", "Q3", "Q5", "Q7"],
  "Jeep": ["Wrangler", "Cherokee", "Grand Cherokee", "Renegade", "Compass"],
  "Peugeot": ["208", "2008", "301", "308", "3008", "Partner", "Rifter"],
  "MG": ["MG5", "ZS", "HS", "RX8", "GT"],
  "Mitsubishi": ["L200", "Mirage", "Outlander", "Montero", "Xpander"],
  "Fiat": ["Mobi", "Uno", "Argo", "Ducato", "Palio"],
  "Subaru": ["Impreza", "XV", "Forester", "Outback", "BRZ"]
};
